accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
  url(r'^$', views.index, name='index'),
  url(r'^signup/$', views.signup, name='signup'),
  url(r'^logout/$', auth_views.logout, {'next_page' : '/'}),
]

home/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from home import views

app_name = 'home'

urlpatterns = [
  url(r'^$', views.index, name='index'),

  url(r'^logout$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

person/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'person'

urlpatterns = [
  url(r'^create/$', views.create, name='create'),
  url(r'^edit/(?P<id>\d+)/$', views.edit, name='edit'),
  url(r'^delete/(?P<id>\d+)/$', views.delete, name='delete'),
  url(r'^list/$', views.list, name='list'),
  url(r'^(?P<id>\d+)/$', views.view, name='view'),
]

reviewus/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin

urlpatterns = [
  url(r'^admin/', admin.site.urls),
  url(r'^accounts/', include('accounts.urls', namespace='accounts')),
  url(r'^program/', include('program.urls', namespace='program')),
  url(r'^broadcasts/', include('broadcastsystem.urls', namespace='broadcasts')),
  url(r'^review/', include('review.urls', namespace='review')),
  url(r'^person/', include('person.urls', namespace='person')),
  url(r'', include('django.contrib.auth.urls')),
  url(r'', include('home.urls')),
  url(r'', include('episode.urls', namespace='episode')),
  url(r'', include('social_django.urls', namespace='social'))
]

home/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from reviewus.db import DBManager as DB


def index(request):
  if not request.user.is_authenticated():
    return render(request, 'home/index.html')

  sql = 'SELECT R.*, U.username, U.first_name, U.last_name, E.title as episode_title, E.program_id, \
             P.title as program_title \
         FROM ru_review as R, auth_user as U, ru_episode as E, ru_program as P \
         WHERE R.author_id = U.id AND R.episode_id = E.id AND E.program_id = P.id \
         ORDER BY R.creation_time desc \
         LIMIT 10'
  user_reviews = DB.execute_and_fetch_all(sql, as_list=True)

  statistic = {
    'reviews': 0, 'episodes': 0, 'stars': 0
  }

  for row in user_reviews:
    name = row['last_name']
    for i in row['first_name'] or []:
      name += '*'
    row['display_name'] = name

  try:
    sql = 'SELECT count(id) as count FROM ru_episode'
    statistic['episodes'] = DB.execute_and_fetch(sql, as_row=True)['count']

    sql = 'SELECT count(id) as count, sum(star) as stars FROM ru_review'
    row = DB.execute_and_fetch(sql, as_row=True)
    statistic['reviews'] = row['count']
    statistic['stars'] = row['stars']
  except:
    pass

  return render(request, 'home/main.html', {
    'user': request.user,
    'user_reviews': user_reviews,
    'statistic': statistic
  })

templates/home/index.html
{% extends 'reviewus/fullscreen.html' %}

{% load staticfiles %}

{% block site_title %}Review Us - Login{% endblock %}

{% block css %}
<style>
body {
  margin: 0px;
  padding: 0px;
  overflow-x: hidden;
  overflow-y: hidden;
  min-width: 320px;
  background: #FFFFFF;
  font-size: 14px;
  line-height: 1.4285em;
  color: rgba(0, 0, 0, 0.87);
  font-smoothing: antialiased;
}
body > .grid {
  height: 100%;
}

.grid .column {
  max-width: 360px;
}
.ui.header>.image:not(.icon), .ui.header>img {
  width: 2em;
  margin-bottom: 0.5em;
}

.background {
  background-image: url({% static 'images/background.jpg' %});
  background-size: 100%;
  background-position: 0 0%;
  height: 100%;
  animation: animatedBackground 40s linear;
  -ms-animation: animatedBackground 40s linear;
  -moz-animation: animatedBackground 40s linear;
  -webkit-animation: animatedBackground 40s linear;
  z-index: -1;
}

.content {
  width: 100%;
  max-width: 760px;
  height: 560px;
  display: block;
  position: absolute;
  left: 50%;
  top: 50%;
  margin-left: -380px;
  margin-top: -280px;
  text-align: center;
  padding: 80px 20px;
  border-radius: 5px;
  box-shabow: rgba(0,0,0,.35) 0 5px 10px;
  z-index: 5;
}
.content .content-wrapper .title {
  color: rgba(255,255,255,.8);
  font-size: 7.5em; 
  font-family:'Righteous', monospace;
}

/* Smartphones (portrait) */
@media only screen and (max-width : 320px) {
  .content .content-wrapper .title {
    font-size: 2rem;
  }
}

@media screen and (max-width: 760px) {
  .content {
     margin: 0 auto;
     left: 2.5%;
     top: 2.5%;
     width: 95%;
     height: 95%;
     padding: 2rem 1rem;
  }
  .content .content-wrapper .title {
     font-size: 4rem;
     margin: 0;
  }
}
</style>
{% endblock %}

{% block nav %}{% endblock %}
{% block footer %}{% endblock %}

{% block content %}

<div class="background"></div>

<div class="content" style="color: white; background: url({% static 'images/background_index.jpg'%}) center center no-repeat; background-size: cover;">
  <div class="content-wrapper">
    <h1 class="title">REVIEW US</h1>
    <br>
    <p class="login">이미 회원이신가요?&nbsp;&nbsp;</p>
    <a class="ui large secondary button" href="{% url 'login' %}">
      로그인
    </a>
    <br>
    <h4 class="ui horizontal divider header" style="color: white;">
      또는
    </h4>
    <div class="ui vertical labeled icon buttons">
      <a class="ui fluid large facebook button" href="{% url 'social:begin' 'facebook' %}" style="margin-top: 1em;">
        <i class="facebook icon"></i>
        Facebook으로 가입하기
      </a>
      <a class="ui fluid large orange button" href="{% url 'accounts:signup' %}" style="margin-top: 1em;">
        <i class="mail icon"></i>
         이메일로 가입하기
      </a>
    </div>
  </div>
</div>

{% endblock %}

{% block script %}
<script>
  function goingup(){
    var s = $(".background")[0].style;
    var p = parseFloat(s.backgroundPositionY || 0) + 0.1;
    s.backgroundPositionY = p + '%';
  }
  var t = setInterval(goingup, 50);
</script>
{% endblock %}

templates/home/main.html
{% extends 'reviewus/base.html' %}

{% load staticfiles %}
{% load humanize %}

{% block site_title %}리뷰어스{% endblock %}

{% block content %}

<!-- Page Contents -->
  <div class="ui inverted vertical masthead center aligned segment" style="margin-top: -1rem;">
    <div class="ui text container">
      <h1 class="ui inverted header">
        안녕하세요, <br /><span>{ {{ user.username }} }</span>님!
      </h1>
      <h2>“Carpe Diem. Seize the day, boys”<br>(Dead Poets Society, 1989)</h2>
      <br>
      <a href="{% url 'episode:list' %}" class="ui huge basic inverted button"><i class="film icon"></i>&nbsp; 최신 에피소드들</a>
      <a href="{% url 'program:list' %}" class="ui huge primary button">프로그램 목록 <i class="right arrow icon"></i></a>
    </div>

  </div>

  <div class="ui vertical segment">
    <div class="ui container">
      <h1 class="ui dividing header">최근 10개의 평가 <small><a href="{% url 'review:list' %}">더보기</a></small></h1>
      <table class="ui table">
      <thead>
        <tr>
          <th>사용자</th>
          <th>프로그램명</th>
          <th>에피소드</th>
          <th>한줄평</th>
          <th>평점</th>
					<th></th>
        </tr>
      </thead>
      <tbody>
      {% for r in user_reviews %}
      <!-- {{ r }} -->
        <tr>
          <td>{{ r.display_name }}</td>
          <td><a href="{% url 'program:view' r.program_id %}">{{ r.program_title }}</a></td>
          <td><a href="{% url 'episode:view' r.episode_id %}">{{ r.episode_title }}</a></td>
          <td>{{ r.comment }}</td>
          <td><div class="ui star rating" data-rating="{{ r.star }}" data-max-rating="5"></div></td>
					<td><div class="ui label basic compact">{{ r.creation_time | naturaltime }}</div></td>
        </tr>
      {% endfor %}
      </tbody>
      </table>
    </div>
  </div>

  <div class="ui vertical stripe segment">
    <div class="ui container">
      <div class="ui three statistics" id="statistics">
        <div class="blue statistic">
          <div class="value">
            <i class="film icon"></i>&nbsp;<span id="st_episodes">0</span>
          </div>
          <div class="label">Episodes</div>
        </div>
        <div class="statistic">
          <div class="value">
            <span id="st_reviews">0</span>
          </div>
          <div class="label">Reviews <i class="thumbs up icon"></i></div>
        </div>
        <div class="yellow statistic">
          <div class="value">
            <i class="star icon"></i>&nbsp;<span id="st_stars">0</span>
          </div>
          <div class="label">Stars</div>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

{% block script %}
<script>
$(function(){
  $('.ui.rating').rating('disable');

  var t;

  function step(id, limit){
    var el = $("#"+id);
    var a = parseInt(el.text());
    var m = parseInt(limit || 0);
    if( a < m ) a += Math.max(1, limit / 90);
    if( a >= m ) a = m;
    el.text(parseInt(a));
    return a >= m;
  } 

  function grow(){
    var x = step("st_reviews", '{{ statistic.reviews }}');
    x &= step("st_stars", '{{ statistic.stars }}');
    x &= step("st_episodes", '{{ statistic.episodes }}');
    if(x) clearInterval(t);
  }

  function start(){
    console.log('a');
    t = setInterval(grow, 15);
  }

  $("#statistics")
    .visibility({
      onTopVisible: start
    })
  ;
});
</script>
{% endblock %}

{% block css %}

  <style type="text/css">

    .hidden.menu {
      display: none;
    }

    .masthead.segment {
      /* min-height: 700px; */
      padding: 1em 0em;
    }
    .masthead .logo.item img {
      margin-right: 1em;
    }
    .masthead .ui.menu .ui.button {
      margin-left: 0.5em;
    }
    .masthead h1.ui.header {
      margin-top: 0em;
      margin-bottom: 0em;
      font-size: 4em;
      font-weight: normal;
    }
    .masthead h2 {
      font-size: 1.7em;
      font-weight: normal;
    }

    .masthead .ui.text.container {
      padding: 3em 0;
    }

    .ui.vertical.stripe {
      padding: 8em 0em;
    }
    .ui.vertical.stripe h3 {
      font-size: 2em;
    }
    .ui.vertical.stripe .button + h3,
    .ui.vertical.stripe p + h3 {
      margin-top: 3em;
    }
    .ui.vertical.stripe .floated.image {
      clear: both;
    }
    .ui.vertical.stripe p {
      font-size: 1.33em;
    }
    .ui.vertical.stripe .horizontal.divider {
      margin: 3em 0em;
    }

    .quote.stripe.segment {
      padding: 0em;
    }
    .quote.stripe.segment .grid .column {
      padding-top: 5em;
      padding-bottom: 5em;
    }

    .footer.segment {
      padding: 5em 0em;
    }

    .secondary.pointing.menu .toc.item {
      display: none;
    }

    @media only screen and (max-width: 700px) {
      .ui.fixed.menu {
        display: none !important;
      }
      .secondary.pointing.menu .item,
      .secondary.pointing.menu .menu {
        display: none;
      }
      .secondary.pointing.menu .toc.item {
        display: block;
      }
      .masthead.segment {
        min-height: 350px;
      }
      .masthead h1.ui.header {
        font-size: 2em;
        margin-top: 1.5em;
      }
      .masthead h2 {
        margin-top: 0.5em;
        font-size: 1.5em;
      }
    }


  </style>
{% endblock %}