episode/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'episode'

urlpatterns = [
  url(r'^episode/', include([
    url(r'^edit/(?P<id>\d+)/$', views.edit, name='edit'),
    url(r'^delete/(?P<id>\d+)/$', views.delete, name='delete'),
    url(r'^list(?:/(?P<page>\d+))?/$', views.list, name='list'),
    url(r'^(?P<id>\d+)(?:/(?P<page>\d+))?/$', views.view, name='view'),
  ])),

  url(r'^program/(?P<program_id>\d+)/episode/', include([
    url(r'^add/$', views.create_with_program, name='create_with_program'),
    url(r'^(?P<nth>\d+)/$', views.view_nth_with_program, name='view_nth_with_program'),
  ])),
]

home/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from home import views

app_name = 'home'

urlpatterns = [
  url(r'^$', views.index, name='index'),

  url(r'^logout$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

reviewus/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin

urlpatterns = [
  url(r'^admin/', admin.site.urls),
  url(r'^accounts/', include('accounts.urls', namespace='accounts')),
  url(r'^program/', include('program.urls', namespace='program')),
  url(r'^broadcasts/', include('broadcastsystem.urls', namespace='broadcasts')),
  url(r'^review/', include('review.urls', namespace='review')),
  url(r'^person/', include('person.urls', namespace='person')),
  url(r'', include('django.contrib.auth.urls')),
  url(r'', include('home.urls')),
  url(r'', include('episode.urls', namespace='episode')),
  url(r'', include('social_django.urls', namespace='social'))
]

episode/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from reviewus.db import DBManager as DB
import reviewus.apis as API


def get_review_info(episode_id):
    sql = 'SELECT AVG(star) AS avg_star, COUNT(star) AS total_star \
           FROM ru_review \
           WHERE episode_id = %s'
    try:
        res = DB.execute_and_fetch(sql, param=(episode_id), as_row=True)
    except:
        pass
    return res


def list(request, page):
    cur_page = int(page or 1)
    episodes = API.get_episodes(page)

    if not episodes:
        raise Http404

    for ep in episodes:
        ep['reviews'] = get_review_info(ep['id'])
        ep['program'] = API.get_program(ep['program_id'])

    return render(request, 'episode/list.html', {
        'page': {
            'prev': max(1, cur_page - 1),
            'cur' : cur_page,
            'next': cur_page + 1
        },
        'episodes': episodes
    })


@staff_member_required
def create(request):
    pass


def view(request, id, page=1):
    eid = int(id or 0)
    page = int(page or 1)
    episode = API.get_episode(eid)

    if not episode:
        raise Http404

    episode['reviews'] = get_review_info(eid)
    program = API.get_program(episode['program_id'])

    sql = 'SELECT R.*, U.username, U.first_name, U.last_name, E.title as episode_title, E.program_id, \
             P.title as program_title \
           FROM ru_review as R, auth_user as U, ru_episode as E, ru_program as P \
           WHERE R.author_id = U.id AND R.episode_id = E.id AND E.program_id = P.id \
             AND E.id = %s \
           ORDER BY R.creation_time desc \
           LIMIT %s, %s'
    data = (
        eid, (page - 1) * 10, 10
    )
    reviews = DB.execute_and_fetch_all(sql, param=data, as_list=True)

    for r in reviews:
        u = r['last_name']
        u += '*' * min(3, len(r['first_name'] or []))
        r['display_name'] = u

    sql = 'SELECT distinct P.id, P.name\
    FROM ru_cast AS C, ru_episode AS E, ru_person AS P\
    WHERE C.episode_id = E.id AND C.person_id = P.id AND E.id = %s\
    ORDER BY P.name'
    casting = DB.execute_and_fetch_all(sql, param=(eid,), as_list=True)

    print(casting)

    return render(request, 'episode/view.html', {
        'episode': episode,
        'program': program,
        'reviews': reviews,
        'casting': casting,
        'page': {
            'prev': max(1, page - 1),
            'cur' : page,
            'next': page + 1
        }
    })


@staff_member_required
def edit(request, id):
    eid = int(id or 0)
    episode = API.get_episode(eid)

    if not episode:
        raise Http404

    if request.method == 'POST':
        if API.update_episode(request.body, id= id) is None:
            raise Http404

        return redirect('episode:view', id= id)

    program = API.get_program(episode['program_id'])

    return render(request, 'episode/edit.html', {
        'episode': episode,
        'program': program
    })


@staff_member_required
def delete(request, id):
    eid = int(id or 0)
    episode = API.get_episode(eid)

    if not episode:
        raise Http404

    if request.method == 'POST':
        API.delete_episode(eid)
        return redirect('episode:list')

    sql = 'SELECT COUNT(id) as reviews FROM ru_review WHERE episode_id = %s'
    res = DB.execute_and_fetch(sql, param=(eid), as_row=True)
    episode['reviews'] = res['reviews']

    return render(request, 'episode/delete.html', {
        'episode': episode,
        'program': API.get_program(episode['program_id'])
    })


"""
###############################
#
# with program id
#
###############################
"""
def create_with_program(request, program_id):
    program = API.get_program(program_id)

    if not program:
        raise Http404

    if request.method == 'POST':
        epi = API.create_episode(request.body)

        if not epi:
              raise Http404

        return redirect('program:view', id=program_id)

    return render(request, 'episode/form.html', {
        'program': program
    })


def view_nth_with_program(request, program_id, nth):
    program = API.get_program(program_id)

    if not program:
        raise Http404

    return redirect('program:view', id= program_id)

templates/episode/delete.html
{% extends 'reviewus/base.html' %}

{% load staticfiles %}
{% load humanize %}

{% block site_title %}리뷰어스 - 에피소드 삭제{% endblock %}

{% block content %}
<div class="ui container">

  <br><br>

  {% include 'program/nav.html' with program=program episode=episode %}

  <h1 class="dividing header">{{ episode.title }}</h1>
  <p><i class="calendar icon"></i> {{ episode.airdate | date | naturalday | default:"미정" }}</p>
  <blockquote class="basic">{{ episode.content | linebreaksbr | truncatewords:50 }}</blockquote>

  <div class="ui red message">
    <div class="header">
      주의!
    </div>
    <p>이 에피소드에는 총 <strong>{{ episode.reviews | default:"0" | add:"0" }}</strong>개의 리뷰가 있습니다!</p>
  </div>

  <div class="ui divider"></div>

  <div class="ui red attached message">
    <div class="header">
      정말 삭제하시겠습니까?
    </div>
  </div>
  <form method="POST" class="ui form attached fluid red segment">
    {% csrf_token %}
    <button type="submit" class="ui large button">네, 삭제합니다.</button> &nbsp;
    <a class="ui red large button" href="{% url 'episode:view' episode.id %}">아니오</a>
  </form>

</div>
{% endblock %}

templates/episode/edit.html
{% extends 'reviewus/base.html' %}

{% load staticfiles %}
{% load humanize %}

{% block site_title %}리뷰어스 - 에피소드 수정{% endblock %}

{% block content %}
<div class="ui container">

  <br><br>

  {% include 'program/nav.html' with program=program episode=episode %}

  <div class="ui basic segment">
    <p><i class="calendar icon"></i>&nbsp;{{ episode.airdate | date | naturalday | default:"미정" }}</p>
    <blockquote class="basic">
      {{ episode.content | default:"(내용 없음)" | truncatewords:50 }}
    </blockquote>
  </div>
  
  <div class="ui basic segment">
    {% include 'episode/form.html' with episode=episode program=program %}
  </div>
</div>
{% endblock %}

{% block script %}
<script>
$('.rating').rating('disable');
$('#airdate').calendar({
  type: 'date',
  startMode: 'year',
  formatter: { date: date_formatter }
});
</script>
{% endblock %}

templates/episode/form.html
{% now "Y년 m월 d일" as now %}

<form method="POST" class="ui form" id="form_episode" 
  {% if episode.id %}
  action="{% url 'episode:edit' episode.id %}"
  {% else %}
  action="{% url 'episode:create_with_program' program.id %}"
  {% endif %}
>
  {% csrf_token %}
  <input type="hidden" name="program_id" value="{{ program.id }}" />
  <input type="hidden" name="id" value="{{ episode.id }}" />
  <div class="field">
    <label>제목</label>
    <input type="text" name="title" placeholder="제목" maxlength="50" value="{{ episode.title | default:"#회" }}" required>
  </div>
  <div class="field">
    <label>Description</label>
    <textarea name="content" placeholder="해당 에피소드에 대한 간략한 설명" maxlength="255">{{ episode.content }}</textarea>
  </div>
  <div class="field">
    <label>방영일자</label>
    <div class="ui calendar" id="airdate">
      <div class="ui input left icon">
        <i class="calendar icon"></i>
        <input type="text" name="airdate" placeholder="방영일자" value="{{ episode.airdate | default:now | date:"Y년 m월 d일"}}">
      </div>
    </div>
  </div>
  <button class="ui submit primary button">저장</button>
</form>

<script>
function date_formatter(date, settings) {
  if (!date) return '';
  var day = date.getDate();
  var month = date.getMonth() + 1;
  var year = date.getFullYear();
  return year + '년 ' + month + '월 ' + day + '일';
}

function reload_input(el){
  $(el).val($(el).val())
}

reload_input('[name=airdate]');

$('#form_episode').form({
  fields: {
    title: 'empty'
  }
});
</script>

templates/episode/list.html
{% extends 'reviewus/base.html' %}

{% load staticfiles %}
{% load humanize %}

{% block site_title %}리뷰어스 - 에피소드 목록{% endblock %}

{% block content %}
<div class="ui container">

  <br>

  <div class="ui divided items">
  {% for episode in episodes %}
    <div class="item">
      <div class="image">
        <img src="https://semantic-ui.com//images/wireframe/image.png">
      </div>
      <div class="content">
        <div class="header">
          <a href="{% url 'program:view' episode.program.id %}">{{ episode.program.title }}</a>
          - 
          <a href="{% url 'episode:view' episode.id %}">{{ episode.title }}</a>
        </div>
        <div class="meta">
          <span class="date">
          {% if episode.airdate %} {{ episode.airdate | naturalday }}
          {% else %}미정
          {% endif %}
          </span>
        </div>
        <div class="description">
          {{ episode.content | default:"(내용 없음)" | truncatewords:10 | linebreaks }}</span>
        </div>
        <div class="extra">
          <div class="ui yellow label">{{ episode.program.genre_name }}</div>
          <a href="{% url 'broadcasts:view' episode.program.broadcast_id %}" class="ui label"><i class="record icon"></i> {{ episode.program.broadcast_name }}</a>
        </div>
        <div class="extra">
          <div class="ui rating" data-rating="{{ episode.reviews.avg_star | floatformat:"0" }}" data-max-rating="5"></div>
          총 {{ episode.reviews.total_star | default:"0" }}개의 평가 ({{ episode.reviews.avg_star | default:"0" | floatformat:"2" }})
        </div>
      </div>
    </div>
  {% endfor %}
  </div>

  <div class="ui divider"></div>

  <div style="padding-bottom: 2em; margin-bottom: 2em;">
    <a href="{% url 'episode:list' page.prev %}" class="ui left floated labeled icon button">
      <i class="left arrow icon"></i>
      Prev
    </a>
    <a href="{% url 'episode:list' page.next %}" class="ui right floated labeled icon button">
      <i class="right arrow icon"></i>
      Next
    </a>
  </div>
</div>

{% endblock %}


{% block script %}
<script>
$('.rating').rating('disable');
</script>
{% endblock %}

templates/episode/view.html
{% extends 'reviewus/base.html' %}

{% load staticfiles %}
{% load humanize %}

{% block site_title %}리뷰어스 - 에피소드 목록{% endblock %}

{% block content %}
<div class="ui container">

  <br><br>

  {% include 'program/nav.html' with program=program episode=episode %}

  <div class="ui basic segment">
    <p><i class="calendar icon"></i>&nbsp;{{ episode.airdate | date | naturalday | default:"미정" }}</p>
    <blockquote class="basic">
      {{ episode.content | default:"(내용 없음)" | truncatewords:50 }}
    </blockquote>
  </div>

  <div class="ui floating segment">
  등장인물: 
  {% for p in casting %}
    <a class="ui basic label" href="{% url 'person:view' p.id %}" style="margin:2px;">{{ p.name }}</a>
  {% empty %}
    (추가 예정)
  {% endfor %}
  </div>

  <br>

  <a href="{% url 'episode:list' %}" class="ui left labeled icon button">
    <i class="list icon"></i> 목록으로
  </a>

  {% if request.user.is_staff %}
  <a href="{% url 'episode:edit' episode.id %}" class="ui left labeled icon yellow button">
    <i class="pencil icon"></i> 수정하기
  </a>

  <a href="{% url 'episode:delete' episode.id %}" class="ui right floated icon red button">
    <i class="trash icon"></i>
  </a>

  {% endif %}

  <div class="ui basic segment">
    <h3 class="ui dividing header" id="reviews">한줄평</h3>
    <div class="ui comments">
    {% for r in reviews %}
      <div class="comment">
        <a class="avatar">
          <img src="{% static 'images/user.png' %}">
        </a>
        <div class="content">
          <a class="author">{{ r.display_name }}</a>
          <div class="metadata">
            <div class="date">{{ r.creation_time | naturaltime }}</div>
            <div class="rating">
              <div class="ui rating stars" data-max-rating="5" data-rating="{{ r.stars | floatformat:0 }}"></div>
            </div>
          </div>
          <div class="text">{{ r.comment }}</div>
        </div>
      </div>
    {% endfor %}
    </div>
    <div style="text-align: center;">
    <div class="ui pagination menu">
        <a class="item" href="{% url 'episode:view' episode.id page.prev %}#reviews">이전</a>
        <a class="item" href="{% url 'episode:view' episode.id page.next %}#reviews">다음</a>
    </div>
    </div>
  </div>
</div>
{% endblock %}


{% block script %}
<script>
$('.rating').rating('disable');
</script>
{% endblock %}