home/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from home import views

app_name = 'home'

urlpatterns = [
  url(r'^$', views.index, name='index'),

  url(r'^logout$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

review/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'review'

urlpatterns = [
  url(r'^create/$', views.create, name='create'),
  url(r'^edit/(?P<id>\d+)/$', views.edit, name='edit'),
  url(r'^delete/(?P<id>\d+)/$', views.delete, name='delete'),
  url(r'^list(?:/(?P<page>\d+))?/$', views.list, name='list'),
  url(r'^(?P<id>\d+)/$', views.view, name='view'),
]

reviewus/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin

urlpatterns = [
  url(r'^admin/', admin.site.urls),
  url(r'^accounts/', include('accounts.urls', namespace='accounts')),
  url(r'^program/', include('program.urls', namespace='program')),
  url(r'^broadcasts/', include('broadcastsystem.urls', namespace='broadcasts')),
  url(r'^review/', include('review.urls', namespace='review')),
  url(r'^person/', include('person.urls', namespace='person')),
  url(r'', include('django.contrib.auth.urls')),
  url(r'', include('home.urls')),
  url(r'', include('episode.urls', namespace='episode')),
  url(r'', include('social_django.urls', namespace='social'))
]

review/models.py
from django.db import models

# Create your models here.

review/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from reviewus.db import DBManager as DB
import reviewus.apis as API


def list(request, page=1):
    page = int(page or 1)
    lst = API.get_reviews(page)

    if not lst:
        raise Http404

    return render(request, 'review/list.html', {
        'reviews': lst
    })


@login_required
def create(request):
    if request.method != 'POST':
        raise Http404

    new_id = API.create_review(request.body, request.user.id)
    if new_id is None:
        return HttpResponse('Invalid Form')

    try:
        eid = API.query_from_request(request.body).get('episode_id')
        return redirect('review:list', eid)
    except:
        raise Http404


@login_required
def edit(request, id):
    r = API.get_review(id)

    if not r:
        raise Http404

    if request.method != 'POST':
        return render(request, 'review/form.html', {
            'review': r
        })

    if API.update_review(request.body, id= id) is not None:
        return redirect('review:list')
    else:
        return HttpResponse('Invalid Form')


def view(request, id):
    pass


@login_required
@staff_member_required
def delete(request, id):
    try:
        res = API.delete_review(id)
        pass
    except:
        pass
    return redirect('review:list')

templates/review/_list.html
{% load staticfiles %}
{% load humanize %}

<div class="ui feed">
{% for review in reviews %}
  <div class="event">
    <div class="label" href="#"></div>
    <div class="content">
      <div class="summary">
        [<a href="{% url 'program:view' review.program_id %}">{{ review.program_title }}</a>/<a href="{% url 'episode:view' review.episode_id %}">{{ review.episode_title }}</a>]&nbsp;
        {{ review.comment }}
        <div class="date">{{ review.creation_time | naturaltime }}</div>
      </div>
      <div class="meta">
        <div class="ui rating" data-max-rating="5" data-rating="{{ review.star | floatformat:0 }}"></div>&nbsp;
        {% if request.user.id == review.author_id %}
        <!--<a href="{% url 'review:edit' review.id %}"><i class="pencil icon"></i></a>-->
        <a href="{% url 'review:delete' review.id %}"><i class="trash icon"></i></a>
        {% endif %}
      </div>
    </div>
  </div>
{% endfor %}
</div>

<script>
$(".rating").rating('disable');
</script>

templates/review/form.html
{% extends 'reviewus/base.html' %}

{% load staticfiles %}

{% block site_title %}ReviewUs - 방송사{% endblock %}

{% block container %}

<form class="ui form" method="POST">
  {% csrf_token %}
  <input type="hidden" name="method" value="{{ method }}" />
  <input type="hidden" name="id" value="{{ broadcast.id }}" />
  <h2 class="ui dividing header">방송사</h2>
  <div class="field">
    <label>방송사 이름</label>
    <input type="text" name="name" placeholder="방송사 이름" maxlength="20" value="{{ broadcast.name }}" />
  </div>
  <div class="ui submit green button"><i class="check icon"></i> 저장</div>
</form>

{% endblock %}

{% block script %}
<script>
$(".form").form({
  name: 'empty'
});
</script>
{% endblock %}

templates/review/list.html
{% extends 'reviewus/base.html' %}

{% load staticfiles %}

{% block site_title %}리뷰어스 - 리뷰 목록{% endblock %}

{% block content %}
<div class="ui container">
  {% include 'review/_list.html' with reviews=reviews %}
</div>
{% endblock %}

{% block script %}
{% endblock %}

templates/review/view.html
{% extends 'reviewus/base.html' %}

{% load staticfiles %}

{% block site_title %}{{ broadcast.name }}{% endblock %}

{% block container %}
<div class="ui container">
  <br>
  <h2 class="ui dividing header">방송사: {{ broadcast.name }}</h2>
  <div style="text-align: center;">
    <img class="ui medium rounded image" src="{% static 'images/broadcasts/' %}{{ broadcast.id }}.png" style="margin:0 auto;"/>

    <p style="margin-top: 20px;">
      평균 평점: {{ broadcast.avg_star | floatformat:5 }}
    </p>
    <div class="ui star rating" data-rating="{{ broadcast.avg_star | add:broadcast.avg_star | floatformat:0 }}" data-max-rating="10" style="margin: 0"></div>
  </div>

  <h2 id="programs" class="ui dividing header">{{ broadcast.name }} 프로그램 목록</h2>
  <div class="ui list">
  {% for pro in programs %}
    <div class="item">
      <i class="tv icon"></i>
      <div class="content">
        <div class="header">
          <a href="{% url 'program:view' pro.id %}">{{ pro.title }}</a>
        </div>
        <div class="description">{{ pro.content | default:"설명 없음"| truncatechars:100 }}</div>
      </div>
    </div>
  {% empty %}
    <div class="item">
      <p>준비중</p>
    </div>
  {% endfor %}
  </div>

  {% if request.user.is_staff %}
  <div>
    <a href="{% url 'broadcasts:edit' broadcast.id %}" class="ui labeled icon yellow button">
      <i class="pencil icon"></i> 수정하기
    </a>
    <a href="{% url 'broadcasts:delete' broadcast.id %}" class="ui labeled icon red button">
      <i class="trash icon"></i> 삭제하기
    </a>
  </div> 
  {% endif %}
</div>
{% endblock %}

{% block script %}
<script>
$(".rating").rating('disable');
</script>
{% endblock %}