home/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from home import views

app_name = 'home'

urlpatterns = [
  url(r'^$', views.index, name='index'),

  url(r'^logout$', auth_views.logout, {'next_page': '/'}, name='logout'),
]

person/urls.py
from django.conf.urls import include, url

from . import views

app_name = 'person'

urlpatterns = [
  url(r'^create/$', views.create, name='create'),
  url(r'^edit/(?P<id>\d+)/$', views.edit, name='edit'),
  url(r'^delete/(?P<id>\d+)/$', views.delete, name='delete'),
  url(r'^list/$', views.list, name='list'),
  url(r'^(?P<id>\d+)/$', views.view, name='view'),
]

reviewus/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin

urlpatterns = [
  url(r'^admin/', admin.site.urls),
  url(r'^accounts/', include('accounts.urls', namespace='accounts')),
  url(r'^program/', include('program.urls', namespace='program')),
  url(r'^broadcasts/', include('broadcastsystem.urls', namespace='broadcasts')),
  url(r'^review/', include('review.urls', namespace='review')),
  url(r'^person/', include('person.urls', namespace='person')),
  url(r'', include('django.contrib.auth.urls')),
  url(r'', include('home.urls')),
  url(r'', include('episode.urls', namespace='episode')),
  url(r'', include('social_django.urls', namespace='social'))
]

reviewus/views.py
from django.http import HttpResponse


def index(request):
    return HttpResponse("Hello, world. You're at the index.")

templates/reviewus/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>{% block site_title %}Review us{% endblock %}</title>

  <link rel="stylesheet" type="text/css" href="{% static 'semantic/dist/semantic.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'semantic-calendar/dist/calendar.min.css' %}" />

  {% block css %}
  {% endblock %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic-bugfix.css' %}" />
</head>
<body>
  <!-- header -->
  {% block header %}
  {% endblock %}

  <!-- content -->
  {% block content %}
    <div class="ui container">
      <!-- container -->
      {% block container %}
      {% endblock %}
    </div>
  {% endblock %}
  
  <!-- footer -->
  {% block footer %}
  {% endblock %}
</body>
<script type="text/javascript" src="{% static 'jquery-3.1.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'semantic/dist/semantic.min.js' %}"></script>
<script type="text/javascript" src="{% static 'semantic-calendar/dist/calendar.min.js' %}"></script>
{% block script %}
{% endblock %}
</html>

templates/reviewus/footer.html
{% load staticfiles %}

<div style="clear:both; padding:1.5em 0; margin:0 auto; display:block;"></div>

<div class="ui black inverted vertical footer segment" style="height: 15rem; padding: 4rem 0 1rem;">
  <div class="ui center aligned container">
    <img src="{% static 'images/logo.png' %}" class="ui centered mini image">
    <div class="ui horizontal inverted small divided link list">
      <a class="item" href="{% url 'home:index' %}">리뷰어스 at CSE on Chonbuk National Unversity</a>
    </div>
  </div>
</div>

templates/reviewus/fullscreen.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>{% block site_title %}Review us{% endblock %}</title>

  <link rel="stylesheet" type="text/css" href="{% static 'semantic/dist/semantic.min.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'semantic-calendar/dist/calendar.min.css' %}" />

  {% block css %}
  {% endblock %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/semantic-bugfix.css' %}" />

  <script type="text/javascript" src="{% static 'jquery-3.1.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'semantic/dist/semantic.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'semantic-calendar/dist/calendar.min.js' %}"></script>
</head>
<body>
  {% block nav %}
    {% include 'reviewus/nav.html' %}
  {% endblock %}

  <!-- header -->
  {% block header %}
  {% endblock %}

  <!-- content -->
  {% block content %}
    <div class="ui container">
      <!-- container -->
      {% block container %}
      {% endblock %}
    </div>
  {% endblock %}

  <!-- footer -->
  {% block footer %}
    {% include 'reviewus/footer.html' %}
  {% endblock %}
</body>
{% block script %}
{% endblock %}
</html>

templates/reviewus/nav.html
{% load staticfiles %}

<div class="ui inverted menu" style="height: 3rem; border-radius:0; ">
  <div class="ui container">
    <div class="item">
      <a href="{% url 'home:index' %}">
        <img src="{% static 'images/logo.png' %}" alt="리뷰어스" style="max-width: 2.2rem;"/>
      </a>
    </div>
    <a href="{% url 'program:list' %}" class="item">
      프로그램별
    </a>
    <a href="{% url 'episode:list' %}" class="item">
      에피소드별
    </a>
    <a href="{% url 'broadcasts:list' %}" class="item">
      방송사별
    </a>
    <a href="{% url 'person:list' %}" class="item">
      인물들
    </a>

    <div class="right menu">
      {% if request.user.is_authenticated %}
      <div class="ui dropdown item">
        {{ request.user.username }}님<i class="dropdown icon"></i>
        <div class="menu">
          <a href="{% url 'accounts:index' %}" class="item">내 정보</a>
          <a href="{% url 'logout' %}" class="item">로그아웃</a>
        </div>
      </div>
      {% else %}
      <a href="{% url 'login' %}" class="item">로그인</a>
      {% endif %}
    </div>
  </div>
</div>

{% block script %}
<script>
  $('.dropdown').dropdown();
</script>
{% endblock %}